version: '3.5'

services:
  improv.poa.br:
    image: nginx:mainline-alpine
    container_name: improv.poa.br
    labels:
      - "traefik.frontend.entryPoints=https,http"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:improv.poa.br,improv.local.dona.to"
    volumes:
      - ./public:/usr/share/nginx/html/:ro
    networks:
      - router
    restart: always

networks:
  router:
    external:
      name: router
